// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwfjznvtbddgyrgrsknd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3Zmp6bnZ0YmRkZ3lyZ3Jza25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDQ3MzksImV4cCI6MjA1ODk4MDczOX0.XurPOVoHj3t4aXBfkPmkE9L9D8EKRFO18sbHiNRxQKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);